#!/usr/bin/env python3
"""Rebuild assets/js/search-index.js from the product cards in shop.html.
Run after you add/edit products:  python3 tools/build-search-index.py"""
import re, json, html
s = open('shop.html', encoding='utf-8').read()
g = s[s.index('id="shop-grid"'):]
out = []
for m in re.finditer(r'<li data-cat="([^"]*)" data-brand="([^"]*)"(.*?)</li>\s*(?=<li data-cat|</ul>)', g, re.S):
    body = m.group(3)
    a = re.search(r'<h3[^>]*>\s*<a[^>]*href="([^"]*)"[^>]*>([^<]+)</a>', body)
    im = re.search(r'<img[^>]*\ssrc="([^"]*)"', body)
    pr = re.search(r'class="font-display[^"]*">([^<]+)<', body)
    if not a: continue
    out.append({"name": html.unescape(a.group(2).strip()), "href": a.group(1), "img": im.group(1) if im else "",
                "price": html.unescape(pr.group(1).strip()) if pr else "", "cat": html.unescape(m.group(1)), "brand": html.unescape(m.group(2))})
open('assets/js/search-index.js', 'w', encoding='utf-8').write('/* generated by tools/build-search-index.py */\nwindow.NM_SEARCH=' + json.dumps(out, ensure_ascii=False) + ';\n')
print(len(out), 'products indexed')
